package server

// Frozen silent-discard and reject reasons (design §5.7).
const (
	ReasonUnknownClient          = "discard_unknown_client"
	ReasonAmbiguousClient        = "discard_ambiguous_client"
	ReasonMalformedHeader        = "discard_malformed_header"
	ReasonInvalidLength          = "discard_invalid_length"
	ReasonInvalidCode            = "discard_invalid_code"
	ReasonInvalidAcctAuth        = "discard_invalid_accounting_request_authenticator"
	ReasonInvalidMA              = "discard_invalid_message_authenticator"
	ReasonMissingMA              = "discard_missing_message_authenticator"
	ReasonEAPWithoutMA           = "discard_eap_without_ma"
	ReasonProxyStateWithoutMA    = "discard_proxy_state_without_ma"
	ReasonUnknownAcctStatus      = "discard_unknown_acct_status"
	ReasonAmbiguousIdentity      = "ambiguous_identity"
	ReasonOverload               = "drop_overload"
	ReasonMissingUsername        = "reject_missing_username"
	ReasonConflictingAuth        = "reject_conflicting_auth"
	ReasonCHAPPasswordLength     = "reject_chap_password_length"
	ReasonUnsupportedMethod      = "reject_unsupported_method"
	ReasonBadCredentials         = "reject_bad_credentials"
	ReasonPasswordChangeRequired = "reject_password_change_required"
	ReasonPolicy                 = "reject_policy"
	ReasonInvalidState           = "reject_invalid_state"
	ReasonChallengeExpired       = "reject_challenge_expired"
	ReasonChallengeBinding       = "reject_challenge_binding"
	ReasonChallengeCapacity      = "reject_challenge_capacity"
	ReasonChallenge              = "challenge"
	ReasonUnsupportedEAPMethod   = "reject_unsupported_eap_method"
	ReasonEAPTooLong             = "reject_eap_too_long"
	ReasonInternal               = "internal_error"
	ReasonOK                     = "ok"
	ReasonSessionNotFound        = "session_context_not_found"
	ReasonUnsupportedAttribute   = "unsupported_attribute"
	ReasonMultipleSessions       = "multiple_session_selection"
)
